Preview
=======
+ Ecological analytics
+ Project management
+ Stats?
+ Why program?
+ Why R?
+ Install R
+ Use a calendar
+ Keep a notebook
+ Questions
+ Survey

Day 1

### you 3

### Why program and why R? 2

### Project file structure 5

### Script 1
annotation

### Basic math 5
algebra
relations

not just a calculator!

### Objects 5
y = mx + b
pi
math with objects

### Functions 5
anatomy
cognates

### equals? 1

= and ==
<-

### 1d data 5
- vectors
- c()
- operations on vectors
- indexing

### Help 2
built in
Google
neighbors

### Challenge
1. Is R installed?
2. setup file structure
3. start a script
4a. calculate the area if a circle
4b. create a vector of numbers
5. calculate the area of a.circle for vector
6. calculate the mean
7. mean function, look at help

Day 2
+ Amazing Grace Hopper  
+ debugging tips

+ scientific method

+ data overview 
+ 1d data and indexing
+ sorting
+ order

+ 2d data = cbind 
+ 2d indexing

challenge
1. create a vector
2. sort
3. order
4. order sort
5. compare

1. create several vectors
2. bind
3. name columns


Day 3

Annie J. Easley (https://twitter.com/NSF/status/578999472170012673/photo/1)

20 min
+ Review: 2d indexing
+ sorting
+ importing data (read.csv)
+ summary, str
+ head, tail
+ colnames

1. download data (http://harvardforest.fas.harvard.edu/data/p06/hf065/hf065-01-ants.csv)
2. summarize data
3. sort by site
4. sort matrix based on site
5. re-organize columns
6. create a new object as a sub-matrix

10 min
+ data classes
+ setting the working directory and relative paths
+ exporting (not saving) data

1. set the working directory
2. save the matrix to results

+ plotting
+ scatterplot (axis labels, point size, point shape)

1. make a scatterplot of basal area ~ elevation

20 min
+ stats overview
+ population and sample
+ biological and statistical hypotheses
+ regression
+ plotting a line

+ Brief comment in data, analysis and software ethics and transparency

1. send me a script that does:
   i. imports a dataset from HF (can be the dataset from today)
   ii. sorts a the whole dataset by a column
   iii. makes a plot of two columns 

Day 4

+ Algorithmic thinking (using the tools you have)
   i. Define a task
   ii. Write pseudo-code
   iii. Write "eu"-code
   iv. Debug
   v. Rinse and repeat

+ Writing functions
   i. function name
   ii. function arguments/parameters
   iii. function tasks and output

1. Write a function that calculates the area of a circle, given a radius
2. Write a function that calculates the mean of a vector of numbers

+ the "for" loop

1. make a vector of random numbers using rnorm
2. use your circle area function to calculate the area for each value

+ Apply 

1. instead of a loop, use sapply
2. make a matrix of values and apply your mean function

Final Thoughts

+ getting more help ?????
+ version control (git, subversion, dropbox)
+ data provenance
+ Code for America (http://www.codeforamerica.org/geeks/)
+ Hackathons
